###############################################################################
# MangoShop Configuration File
###############################################################################

# Database Configuration
Database:

    # Username for connecting to the database.
    Username: mc
    # Password for connecting to the database.
    Password: mc
    # This should have three parts: the main URL, the port number, and database name.
    URL: localhost:3306/mc

# Format Replacements
FormatReplacements:

  PREFIX_INFO: '&8[&9!&8] &9Info &8[&9!&8]&7'
  PREFIX_SUCCESS: '&8[&a!&8] &aSuccess &8[&a!&8]&7'
  PREFIX_FAILURE: '&8[&c!&8] &cFailure &8[&c!&8]&7'

# Formatting strings
Formats:

  NoPermission: 'PREFIX_FAILURE You do not have the &f{0}&7 permission.'
  PlayersOnly: 'PREFIX_FAILURE Only players can use &f{0}&7'
  PlayerDataNotLoaded: 'PREFIX_FAILURE Player data has not been loaded yet.'
  PlayerOffline: 'PREFIX_FAILURE Player &f{0}&7 is offline.'
  TooManyAutoCompleteMatches: 'PREFIX_FAILURE Multiple online players match &f{0}&7.'
  PlayerLocked: 'PREFIX_FAILURE You are locked. Please wait until your data is loaded or saved.'

  MovingToMessage: 'PREFIX_SUCCESS Moving to &f{0}&7 ...'
  MovingOtherToMessage: 'PREFIX_SUCCESS Moving &f{0}&7 to {1} ...'
  CurrentServer: 'PREFIX_INFO Current server: &f{0}&7'
  OnlineServerList: 'PREFIX_INFO Online Servers: &f{0}&7'
  ServerOffline: 'PREFIX_FAILURE Server &f{0}&7 is offline.'
  InputIsCurrentServer: 'PREFIX_FAILURE &f{0}&7 is the current server.'
  OtherAlreadyOnServer: 'PREFIX_FAILURE &f{0}&7 is already on {1}.'
  BlockedServer: 'PREFIX_FAILURE Server &f{0}&7 is blocked for you.'

  SocialSpyUsage: 'PREFIX_INFO /socialspy <all|world|none>'
  SocialSpyChange: 'PREFIX_SUCCESS SocialSpy set to &f{0}&7'

  DVanishUsage: 'PREFIX_INFO /dvanish <on|off>'
  DVanishChange: 'PREFIX_SUCCESS DeltaVanish set to &f{0}&7'

  TeleportDenyUsage: 'PREFIX_INFO /tpdeny <on|off>'
  TeleportDenyChange: 'PREFIX_SUCCESS TeleportDeny set to &f{0}&7'

  LockdownUsage: 'PREFIX_INFO /lockdown <on|off>'
  LockdownMessage: 'Server is locked down ... for reasons!'
  LockdownChange: 'PREFIX_SUCCESS Lockdown set to &f{0}&7'

  DeltaEssentialsUsage: 'PREFIX_INFO /deltaessentials <debug|reload>'
  DeltaEssentialsDebugUsage: 'PREFIX_INFO /deltaessentials debug <on|off>'
  DeltaEssentialsDebugChange: 'PREFIX_SUCCESS DeltaEssentials debug set to &f{0}&7'
  DeltaEssentialsReloaded: 'PREFIX_SUCCESS DeltaEssentials configuration reloaded.'

  TellUsage: 'PREFIX_INFO /tell <name> <message>'
  ReplyUsage: 'PREFIX_INFO /reply <message>'
  NoReplyTarget: 'PREFIX_FAILURE You do not have anyone to reply to.'

  TellLog: '[{0} -> {1}] {2}'
  TellSpy: '&8[&7Spy&8]&7=&8[&7{0} &8-> &7{1}&8] &7{2}'
  TellSender: '&8[&dPM&8]&7=&8[&eMe -> {0}&8] &d{1}'
  TellReceiver: '&8[&dPM&8]&7=&8[&e{0} -> Me&8] &d{1}'

  TeleportUsage: 'PREFIX_INFO /tp <name>'
  TeleportRequestUsage: 'PREFIX_INFO /tpahere <name>'
  TeleportHereUsage: 'PREFIX_INFO /tphere <name>'
  NoPendingTeleportRequest: 'PREFIX_FAILURE You do not having a pending teleport request.'
  SentTeleportRequest: 'PREFIX_SUCCESS You sent &f{0}&7 a teleport request.'
  ReceivedTeleportRequest: 'PREFIX_SUCCESS &f{0}&7 sent you a teleport request. Type /tpaccept to accept within 30 seconds.'

  TeleportingMessage: 'PREFIX_SUCCESS Teleporting to &f{0}&7 ...'
  TeleportedToYou: 'PREFIX_INFO &f{0}&7 teleported to you.'
  DeniedTeleport: 'PREFIX_INFO &f{0}&7 was denied a teleport to you.'
  OtherDenyingTeleport: 'PREFIX_FAILURE &f{0}&7 is denying teleports.'
  UnsafeLocation: 'PREFIX_FAILURE &f{0}&7 is not in a safe location.'

# Debug Mode
DebugMode: False
